config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'

  resources :products do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord

  has_many :reviews

  validates :name, :description, :price_in_cents, :image_url, presence: true
  validates :price_in_cents, numericality: {only_integer: true}

def price_in_dollars
  price_in_dollars = price_in_cents.to_f / 100
  sprintf("$%.2f", price_in_dollars)
end

end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :product

  validates :comment, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new

    @product.name = params[:product][:name]
    @product.description = params[:product][:description]
    @product.price_in_cents = params[:product][:price_in_cents]
    @product.image_url = params[:product][:image_url]

    if @product.save
      flash[:notice] = "Product successfully created"
      redirect_to '/products'

    else
      render :new
    end

  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
     if @product.update(product_params)
       flash[:notice] = "Product successfully updated"
       redirect_to @product
      else
       redirect_back_or_to @product
     end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Product successfully deleted"
    redirect_to products_path
  end

  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents, :image_url)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @product = Product.find(params[:product_id])
    @review = Review.all
    render product_reviews_path
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
  end

  def update

    @review = Review.find(params[:id])
     if @review.update(review_params)
       flash[:notice] = "Review successfully updated"
       redirect_to product_path
      else
       redirect_back_or_to @product
     end
  end

  def new
    @product = Product.find(params[:product_id])
    @review = Review.new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    @review.comment = params[:review][:comment]
    @review.name = params[:review][:name]

    if @review.save
      flash[:notice] = "Review successfully created"
      redirect_to @product

    else
      flash[:notice] = "Something went wrong"
      render :new
    end
  end

  def show
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end

  def destroy
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to @product
  end

  def review_params
    params.require(:review).permit(:name, :comment)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rainforest2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <link href="https://fonts.googleapis.com/css?family=Bungee+Shade|VT323" rel="stylesheet">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Rainforest</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/shop-homepage.css" rel="stylesheet">
    <link href="css/shop-item.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
       <div class="container">
           <!-- Brand and toggle get grouped for better mobile display -->
           <div class="navbar-header">
               <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                   <span class="sr-only">Toggle navigation</span>
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
               </button>
               <a class="navbar-brand" href="#">Rainforest</a>
           </div>
           <!-- Collect the nav links, forms, and other content for toggling -->
           <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
               <ul class="nav navbar-nav">
                   <li>
                       <%= link_to("Browse All Items", "/products") %>
                   </li>
                   <li>
                       <%= link_to("Add an Item", "/products/new") %>
                   </li>
               </ul>
           </div>
           <!-- /.navbar-collapse -->
       </div>
       <!-- /.container -->
     </nav>

      <% if flash[:notice] %>
        <p class="notice"><%= flash[:notice] %></p>
      <% end %>
      <% if flash[:alert] %>
        <p class="alert"><%= flash[:alert] %></p>
      <% end %>

    <%= yield %>


            <!-- Footer -->
            <footer>
                <div class="row">
                    <div class="col-lg-12">
                        <p>Copyright &copy; JD/Bitmaker 2017</p>
                    </div>
                </div>
            </footer>
  </body>

</html>

app/views/products/_product_form.html.erb
<% if @product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited this item from being saved:</h2>

   <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @product do |f| %>
<p>
  <%= f.label :name %>
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :description %>
  <%= f.text_field :description %>
</p>
<p>
  <%= f.label :price_in_cents %>
  <%= f.text_field :price_in_cents %>
</p>
<p>
  <%= f.label :image_url %>
  <%= f.text_field :image_url %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/products/_single_product.html.erb
<div class="single_product">
  <h3>Name: <%= @product.name %> </h3>
  <p>Description: <%= @product.description %></p>
  <p>Price: <%= @product.price_in_dollars %></p>
</div>

app/views/products/edit.html.erb
<div class="editpage">


<h1>Editing <%= link_to @product.name, product_path(@product) %> </h1>
<%= render 'product_form', single_product: @product %>
<%= link_to 'Back to Item', product_path %>

</div>

app/views/products/index.html.erb
<div class="container">

       <div class="row">

           <div class="col-md-3">
               <p class="lead">All Items</p>
           </div>

           <div class="col-md-9">

               <div class="row carousel-holder">

               <div class="row">

                          <% @products.each do |product| %>
                   <div class="col-sm-4 col-lg-4 col-md-4">
                       <div class="thumbnail">
                          <%= image_tag product.image_url, :size => "160x320" unless product.image_url.blank? %>
                           <div class="caption">
                               <h4 class="pull-right"><%= product.price_in_dollars %></h4>

                               <h4><%= link_to "/products/#{product.id}" do %>
                               <%= product.name %></a></h4>
                               <% end %>
                               <p><%= product.description%>.</p>
                           </div>
                           <div class="ratings">
                               <p class="pull-right"><%= product.reviews.count %> reviews</p>
                               <p>
                                   <span class="glyphicon glyphicon-star"></span>
                                   <span class="glyphicon glyphicon-star"></span>
                                   <span class="glyphicon glyphicon-star"></span>
                                   <span class="glyphicon glyphicon-star"></span>
                                   <span class="glyphicon glyphicon-star"></span>
                               </p>
                           </div>
                       </div>
                   </div>
       <% end %>


                       </div>
                   </div>

               </div>

           </div>

       </div>

   </div>
   <!-- /.container -->

   <div class="container">

       <hr>

app/views/products/new.html.erb
<div class="newproductform">



<h2>Add a New Product</h2>

<%= render 'product_form', single_product: @product %>

</div>

app/views/products/show.html.erb
<div class="container">

      <div class="row">

          <div class="col-md-9">

              <div class="thumbnail1">
                  <%= image_tag @product.image_url %>
                  <div class="caption-full">
                      <h4 class="pull-right"><%= @product.price_in_dollars %></h4>
                      <h4><a href="#"><%= @product.name %></a>
                      </h4>
                      <p><%= @product.description %></p>
                  </div>
                  <div class="ratings">
                      <p class="pull-right"><%= @product.reviews.count %> reviews</p>
                      <p>
                          <span class="glyphicon glyphicon-star"></span>
                          <span class="glyphicon glyphicon-star"></span>
                          <span class="glyphicon glyphicon-star"></span>
                          <span class="glyphicon glyphicon-star"></span>
                          <span class="glyphicon glyphicon-star-empty"></span>
                          4.0 stars
                      </p>
                  </div>
              </div>
              <div class="editdeletebar">
                <%= link_to 'Edit', edit_product_path %> |
                <%= link_to 'Delete', product_path(@product), method: :delete, data: {confirm: "Are you sure you want to delete the product '#{@product.name}'? This cannot be undone!"} %>
              </div>
              <br>
              <br>
              <hr>
              <div class="well">

                  <div class="text-right">
                      <div class="btn btn-success"><%= link_to 'Leave a Review', new_product_review_path(@product), :class => "btn" %></div>

                  </div>

                  <hr>
                  <% @product.reviews.each do |review| %>
                  <div class="row">
                      <div class="col-md-12">

                          <span class="reviewername">Reviewer:</span> <%= review.name %>
                          <span class="pull-right">Created at: <%= review.created_at %></span>
                          <p><%= review.comment %></p>
                          <%= link_to 'Delete', product_review_path([@product, @review]), method: :delete, data: {confirm: "Are you sure you want to delete the review? This cannot be undone!"} %>
                      </div>
                  </div>
                  <hr>

                  <% end %>

              </div>

          </div>

      </div>

  </div>
  <!-- /.container -->

  <div class="container">

      <hr>

app/views/reviews/_review_form.html.erb
<div class="reviewform">



<%= form_for([@product, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
<h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

<ul>
<% @review.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>


<div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :comment %><br />
  <%= f.text_area :comment %>
</div>
<div class="actions">
<%= f.submit %>
</div>
<% end %>

</div>

app/views/reviews/_single_review.html.erb
<div class="single_review">
  <h3>Name: <%= @product.review.name %> </h3>
  <p>Description: <%= @product.review.comment %></p>
</div>

app/views/reviews/new.html.erb
<%= render 'review_form', single_review: @review %>